server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patients
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: patient-service
debug: true
